name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: '6.0.5'

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build-win
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: uby-agendamentos-windows
        path: |
          dist/*.exe
          dist/*.zip
        retention-days: 30
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*.exe
          dist/*.zip
        draft: false
        prerelease: false
        generate_release_notes: true
        name: "UBY Agendamentos v${{ github.ref_name }}"
        body: |
          ## 🚀 Nova versão do UBY Agendamentos
          
          ### ✨ Novidades desta versão:
          - Correções de bugs e melhorias de performance
          - Interface otimizada para Windows 10 e 11
          - Sistema de notificações aprimorado
          - Melhorias no sistema de agendamentos
          
          ### 📥 Downloads disponíveis:
          - **Instalador NSIS**: Para instalação completa no sistema
          - **Versão Portátil**: Para execução sem instalação
          
          ### 💻 Requisitos do sistema:
          - Windows 10 ou superior
          - 4GB de RAM (recomendado)
          - 500MB de espaço livre em disco
          
          ---
          
          **Desenvolvido por L34NDR0-DEV**
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}